/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chapter02;

public class App {
    public String getGreeting() {
        return "Observer app test";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        var weatherData = new WeatherData();
        var currentDisplay = new CurrentConditionsDisplay(weatherData);
        var statisticsDisplay = new StatisticsDisplay(weatherData);
        var forecastDisplay = new ForecastDisplay(weatherData);

        weatherData.setMeasurements(80, 65, 30.4f);
        weatherData.setMeasurements(82, 70, 29.2f);
        weatherData.setMeasurements(78, 90, 29.2f);
    }
}
