/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chapter01;

public class App {
    public String getGreeting() {
        return "Strategy app test";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Duck[] ducks = {
            new MallardDuck(),
            new RedheadDuck(),
            new RubberDuck(),
            new DecoyDuck()
        };

        for (Duck duck: ducks) {
            duck.swim();
            duck.fly();
            duck.quack();
        }

        var modelDuck = new ModelDuck();
        modelDuck.fly();
        modelDuck.setFlyBehavior(new FlyRocketPowered());
        modelDuck.fly();
    }
}
