/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chapter05;

public class App {
    public String getGreeting() {
        return "Singleton app test";
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Runnable task = () -> {
            for (int i = 0; i < 999; i++) {
                Singleton.getInstance().getCounter();
                try {
                    Thread.currentThread().sleep(1);
                } catch (InterruptedException e) {
                }
            }
            System.out.println(Singleton.getInstance().getCounter());
        };
        
        new Thread(task).run();
        new Thread(task).run();
    }
}
